version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: piscoc1_postgres_only
    environment:
      POSTGRES_DB: multi_platform_integration
      POSTGRES_USER: piscoc1_user
      POSTGRES_PASSWORD: piscoc1_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U piscoc1_user -d multi_platform_integration"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data: